### ISSUE TITLE
Lsyncd Status

### ISSUE THREAD

**Issue by LukeHandle** [stevekaten/cloud-monitoring-plugin-deploy#1]
Hi there. Thanks for recreating this repo after it was deleted.

I believe there used to be a "lsyncd_status.yml" playbook/role - but I can no longer see these here. Was this repo recreated from an older backup possibly..? If you still have the lsyncd roles, that's great, if not, I understand.

Thanks again!

**Comment by stevekaten** [comment]
Looks like it did get deleted.  I found an old racker has it available:

https://github.com/stephenlang/cloud-monitoring-plugin-deploy
